### ISSUE TITLE
Doesn't work with the new Q&A features.

### ISSUE THREAD

**Issue by iamjackg** [daattali/gslides-betternotes-extension#10]
Hi there!

First of all, thank you for this extension: it's great. Its only issue is that it doesn't appear to work with the new Q&A feature. I'll show an example:

![image](https://cloud.githubusercontent.com/assets/19474350/20317868/e6694844-ab35-11e6-8896-10d9ea76f9b4.png)

When, I click on 'Start new' to actually activate the Q&A, this happens:

![image](https://cloud.githubusercontent.com/assets/19474350/20317881/eebbac8a-ab35-11e6-84a4-0357ac30ea41.png)

I'll try to look more into the actual missing CSS properties, as it seems that this is just a consequence of the Q&A feature being newer than the script.

**Comment by iamjackg** [comment]
I think I found it:

that div has class `punch-viewer-speaker-empty-questions`, which needs to also have the `position: static;` property added to it, but it's not in the extension. Doing that fixes the issue.

**Comment by daattali** [comment]
Hi @iamjackg , thanks for reporting, and more importantly for actually looking into the issue yourself. If you think you've found the problem, do you mind submitting a PR?
