### ISSUE TITLE
Is there an option to relocated the timer 

### ISSUE THREAD

**Issue by meschult** [daattali/gslides-betternotes-extension#12]
This is a great extension that had helped me make much better presentations, as I can use the preview slides as my servants instead of my master.  

Anyway, I notice that the timer takes valuable reading space from the preview slide.  Is there an option to move it, let's say, to the R/H side where the speaker notes reside?    

Thank you so much...

Mynor

**Comment by daattali** [comment]
No there isn't. To be honest, I completely forgot I even made this extension, I haven't had a need for it in years :) If you know how to code then feel free to submit a fix!
