### ISSUE TITLE
Adjust size is broken when using ChromeOS 70.0.3538.76

### ISSUE THREAD

**Issue by brandonezell** [daattali/gslides-betternotes-extension#15]
When opening slide notes, I'm unable to adjust size of speaker notes panel

I'm receiving 2 errors: 

**Error 1**

Refused to execute inline script because it https://docs.google.com/static/presentation/client/js/4113731852-viewer_core.js:862 violates the following Content Security Policy directive: "script-src 'strict-dynamic' 'unsafe-eval' 'unsafe-inline' https: 'nonce-9hLZDR9Qn/XCqSVkTUnDOaxDLSo'". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.

p.Bo @ https://docs.google.com/static/presentation/client/js/4113731852-viewer_core.js:862

**Error 2**

Error in response to storage.get: HierarchyRequestError: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to insert the rule.
    at resizeSlides (chrome-extension://piciggpbidhfbpefjjbomcgomanjfbeb/js/gsbn.js:52:17)
    at Object.addJS (chrome-extension://piciggpbidhfbpefjjbomcgomanjfbeb/js/gsbn.js:121:11)
    at Object.getOptsResp [as callback] (chrome-extension://piciggpbidhfbpefjjbomcgomanjfbeb/js/gsbn.js:22:14)
    at Object.getOptions (chrome-extension://piciggpbidhfbpefjjbomcgomanjfbeb/js/gsbn.js:150:27)
    at Object.init (chrome-extension://piciggpbidhfbpefjjbomcgomanjfbeb/js/gsbn.js:24:12)
    at chrome-extension://piciggpbidhfbpefjjbomcgomanjfbeb/js/gsbn.js:154:6

I receive Error 1 regardless of whether the extension is installed.  Error 2 is only received with the extension installed.

Using ChromeOS 70.0.3538.76 on Pixelbook. @kball @daattali

**Comment by brandonezell** [comment]
Error in response to storage.get: HierarchyRequestError: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to insert the rule.
    at resizeSlides (chrome-extension://piciggpbidhfbpefjjbomcgomanjfbeb/js/gsbn.js:52:17)
    at Object.addJS (chrome-extension://piciggpbidhfbpefjjbomcgomanjfbeb/js/gsbn.js:121:11)
    at Object.getOptsResp [as callback] (chrome-extension://piciggpbidhfbpefjjbomcgomanjfbeb/js/gsbn.js:22:14)
    at Object.getOptions (chrome-extension://piciggpbidhfbpefjjbomcgomanjfbeb/js/gsbn.js:150:27)
    at Object.init (chrome-extension://piciggpbidhfbpefjjbomcgomanjfbeb/js/gsbn.js:24:12)
    at chrome-extension://piciggpbidhfbpefjjbomcgomanjfbeb/js/gsbn.js:154:6

☝☝ Confirmed same error on Windows 10 Pro using Chrome 70.0.3538.77 and earlier Chrome 69.x build. @kball @daattali

**Comment by daattali** [comment]
Thanks for the useful details. Unfortunately I tried on a few machines at home and I'm not able to replicate. I wonder if `sheet` [here](https://github.com/daattali/gslides-betternotes-extension/blob/ae088d93443a03764974205964c41f77169deb9c/js/gsbn.js#L51) is undefined , and if so, then what exactly causes it to not be defined properly.

I'll try on other machines when I get a chance

**Comment by brandonezell** [comment]
No problem. Thanks for looking into it!  For now I can bump up the manual "Width of Notes section (pixels)" option in the extension and get enough margin to live with.  Still better than default!

**Comment by pian1966** [comment]
Thanks for the extension - I love it.
It seems to work fine on my windows machine but as soon as I select any of the options on my Chromebook or Linux (Ubuntu) machine it stops working and reverts back to the standard google presenter view. Thanks for the good work

**Comment by brandonezell** [comment]
@daattali Any updates?

**Comment by daattali** [comment]
Haven't been able to reproduce. Will keep trying other machines

**Comment by daattali** [comment]
If you're familiar with javascript perhaps you can try debugging by inserting a `debugger` statement before the error and see what's going on, if you know how to do that

**Comment by brandonezell** [comment]
Unfortunately, I have limited technical chops.  Maybe you could try it out on a virtual Chrome Machine? https://www.neverware.com/freedownload

**Comment by daattali** [comment]
Interesting project, but seems overkill and very time and resource consuming. I'll have to wait until someone with the technical ability can reproduce or I'm able to

**Comment by daattali** [comment]
I've tested on a few different OS and still cannot see the problem.

Is this happening to you always? Is it happening with the demo document https://docs.google.com/presentation/d/18svsKPFNQrBLOSAmOouD410kX9fuaNp3e1K1GTTBLiU/edit?usp=sharing ?

**Comment by pian1966** [comment]
I seem to have stumbled onto something. The Demo document works fine but when I change the speaker notes font to Calibri, Arial Black, Comfortaa, Fredoka One etc the extension fails - see https://docs.google.com/presentation/d/1HTSjRHQhW_QD-psCEKPrgMZ0zoyMFgktKkNHq_iFZI4/edit?usp=sharing

**Comment by daattali** [comment]
Thank you @pian1966  -- that I was able to reproduce and I'm submitting the fix to the chrome store right now. Please try in about an hour or later and verify that this is fixed.

@brandonezell can you also try in an hour or later to see if this also fixes your issue?

**Comment by brandonezell** [comment]
@daattali It's working for me now.  The template I was using had a custom font for speaker notes as well (Roboto).  I uninstalled the extension and reinstalled to force an update with the fix you pushed and it resolved the issue.  I tried changing the speaker notes font in the the demo deck as well without any issues.  Hope that fixed it for good!

Thanks @pian1966 for spotting the issue!

**Comment by pian1966** [comment]
Thanks for sorting out a fix. It's a great extension - any chance of an option to place "next slide" on the right with the time (would allow a bigger "current slide" for the presenter to read from?

**Comment by daattali** [comment]
That's quite a heavy feature, you're welcome to try it out and submit a pull request if you found a good design and solution for it, but as far as I'm concerned that's outside the scope of this extension
