### ISSUE TITLE
Compatibility with current Chrome/Google slides

### ISSUE THREAD

**Issue by davinkevin** [daattali/gslides-betternotes-extension#16]
Hi, 

Your plugin/extensions is really great but the current version seems to suffer from update on Google slides. 

![image](https://user-images.githubusercontent.com/1970922/98837826-b7345100-2443-11eb-84a2-7d37cf655658.png)

I've checked the source code, but I was not able to found the cause of the bug.
The bar allowing to resize seems to be out of sync with the comment bar.

When I use the bar to resize the slide part, only the left (previous) slides changes its size but the right (next) slides doesn't.

![image](https://user-images.githubusercontent.com/1970922/98839755-39be1000-2446-11eb-8b8f-6a075664123b.png)

Thank for your help. 

BTW, I really like your plugin, but I would love to have a mode with only *current* and *next* slides in full size and nothing else… I will try to develop a plugin for this if possible.

**Comment by daattali** [comment]
Should be fixed now. It might take a few hours until the extension store picks up the change

**Comment by davinkevin** [comment]
Amazing 👍, thank you a lot 💪
