### ISSUE TITLE
Enlarge "upcoming slide" thumbnail as well

### ISSUE THREAD

**Issue by daattali** [daattali/gslides-betternotes-extension#2]
A few people requested this feature, look into it when I have a free day

**Comment by DesktopMan** [comment]
This feature would be much appreciated. It boggles the mind that Google hasn't fixed this. The next slide is so small it's not even remotely useful by default.

**Comment by daattali** [comment]
Currently scrambling to write my thesis, but I completely forgot about this. I'll try to take a look in an upcoming weekend!

**Comment by daattali** [comment]
@DesktopMan done. Please check to make sure this is what you wanted. There is a new options when you click on the icon in the URL toolbar that allows you to resize the next slide

**Comment by DesktopMan** [comment]
Works, thanks a lot :) Google really should redesign the left side of the speaker notes window...

**Comment by daattali** [comment]
Yeah, it's horrible. The new version also lets you manually drag the sidebar to select the size, should be more useful!

**Comment by bradenbird** [comment]
Any chance you could do the same for the previous slide? If it's too complicated don't worry about it, already a great extension!
