### ISSUE TITLE
extra language

### ISSUE THREAD

**Issue by Trendmatcher** [daattali/gslides-betternotes-extension#4]
Can you add NL-nl (Dutch) as a language?

**Comment by daattali** [comment]
I've added it along with a few other languages. It should work in a few hours

**Comment by Trendmatcher** [comment]
Thanks a lot! I'll try first thing tomorrow and write a review on my blog!

**Comment by Trendmatcher** [comment]
Super, now works like a charm, love it!
Thanks again!

**Comment by daattali** [comment]
Thanks for using it!
